# Site settings
name: Hassan El Mghari
title: Hassan El Mghari | Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
description: Entreprenerial full-stack software engineer focused on building beautiful web applications
url: https://hassanelmghari.com
baseurl: ''
email: hassan@hey.com
cover: https://hassanelmghari.com/img/og.png
logo: https://hassanelmghari.com/img/emojis/technologist.png
resume: https://hassanelmghari.com/resume.pdf
social:
  - title: email
    url: mailto:hassan@hey.com
  - title: twitter
    url: https://twitter.com/nutlope
  - title: github
    url: https://github.com/Nutlope
  - title: linkedin
    url: https://www.linkedin.com/in/nutlope/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
